language: python
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3.6
  - sudo apt-get -y install python3.7
  - sudo apt-get -y install python3.8

install:
  - pip install tox

script:
  - tox
